# These are supported funding model platforms
github: helloanaroul
patreon: helloanaroul
ko_fi: helloanaroul
custom: 
  - 'https://buymeacoffee.com/helloanaroul'
  - 'https://buymeacha.com/helloanaroul'
  - 'https://anarul.online'